### ISSUE TITLE
code highlighting: One line comment interpreted as multi line comment?

### ISSUE THREAD

**Issue by MyIgel** [ptrckbnck/SQLChecker#6]
The parser should support one line comments as well, currently after a `--` at the start of a line no other code will be interpreted which leads to no lines being executed. Btw, why is a `#` not supported as a one line comment marker?

**Comment by ptrckbnck** [comment]
You are talking about the code highlighting, right?
The database management system parses the statement. That means, any bugs in code highlighting should not affect code execution at all.

There is actually no reason not to use `#`. I am going to implement it. Also, `--` should not comment muliple lines.

Edit:
Fixed in branch new

**Comment by ptrckbnck** [comment]
Fixed in release 1.0.3d
